version: '3'

services:
  # Сервис для PostgreSQL
  psql_alif:
    image: postgres:16
    container_name: psql_alif
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql_alif_data:/var/lib/postgresql/data

  # Сервис для вашего Go приложения
  alif_go_app:
    build: .
    container_name: alif_go_app
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - psql_alif


volumes:
  postgresql_alif_data:
    driver: local